In [1]:
# Assigning features and label variables
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy',
         'Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool',
      'Mild','Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes',
      'No','Yes','Yes','Yes','Yes','Yes','No']

In [2]:
from sklearn.preprocessing import LabelEncoder

C:\Users\dell\anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [3]:
l=LabelEncoder()

In [8]:
Weather=l.fit_transform(weather)
Weather

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1], dtype=int64)

In [6]:
Temp=l.fit_transform(temp)

In [7]:
Play=l.fit_transform(play)

In [9]:
feature_names=list(zip(Weather,Temp))

In [10]:
feature_names

[(2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2)]

In [11]:
from sklearn.naive_bayes import GaussianNB

In [12]:
g=GaussianNB()

In [13]:
g.fit(feature_names,Play)

GaussianNB(priors=None, var_smoothing=1e-09)

In [14]:
g.predict([[0,0]])

array([1], dtype=int64)

In [15]:
from sklearn.datasets import load_wine

In [16]:
wine=load_wine()

In [17]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [18]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [19]:
wine.data[0:5]

array([[1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, 1.120e+01, 1.000e+02, 2.650e+00,
        2.760e+00, 2.600e-01, 1.280e+00, 4.380e+00, 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, 1.860e+01, 1.010e+02, 2.800e+00,
        3.240e+00, 3.000e-01, 2.810e+00, 5.680e+00, 1.030e+00, 3.170e+00,
        1.185e+03],
       [1.437e+01, 1.950e+00, 2.500e+00, 1.680e+01, 1.130e+02, 3.850e+00,
        3.490e+00, 2.400e-01, 2.180e+00, 7.800e+00, 8.600e-01, 3.450e+00,
        1.480e+03],
       [1.324e+01, 2.590e+00, 2.870e+00, 2.100e+01, 1.180e+02, 2.800e+00,
        2.690e+00, 3.900e-01, 1.820e+00, 4.320e+00, 1.040e+00, 2.930e+00,
        7.350e+02]])

In [20]:
wine.target[0:23]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0])

In [21]:
X=wine.data
y=wine.target

In [22]:
from sklearn.model_selection import train_test_split

In [33]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)

In [34]:
from sklearn.naive_bayes import GaussianNB

In [35]:
g=GaussianNB()

In [36]:
g.fit(X_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [37]:
pred=g.predict(X_test)

In [38]:
pred

array([2, 0, 0, 1, 1, 1, 0, 2, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 2, 0, 2, 1,
       1, 2, 1, 1, 1, 2, 1, 0, 2, 0, 1, 2, 1, 1, 2, 2, 0, 2, 0, 0, 1, 0,
       1, 1, 2, 2, 1, 1, 1, 1, 2, 0])

In [39]:
g.predict([[1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
        3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
        1.065e+03]])

array([0])

In [40]:
from sklearn.metrics import accuracy_score

In [41]:
accuracy_score(pred,y_test)

0.9444444444444444